name: NET7.Features

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore NET7.Features.sln
    - name: Build
      run: dotnet build --no-restore NET7.Features.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal NET7.Features.sln